services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    environment:
      - API_BASE=http://api:3001
    ports:
    - 127.0.0.1:3000:3000
  api:
    build: .
    entrypoint: ["/app/chron-api"]
    environment:
      - CHRON_DATABASE_URI=postgres://postgres:password@postgres:5432/postgres
    volumes:
      - ./config.toml:/app/config.toml
    ports:
    - 127.0.0.1:3001:3001
  ingest:
    build: .
    entrypoint: ["/app/chron-ingest"]
    volumes:
      - ./mnt:/mnt
      - ./config.toml:/app/config.toml
    environment:
      - MAPS_API_KEY=${MAPS_API_KEY}
      - CHRON_DATABASE_URI=postgres://postgres:password@postgres:5432/postgres
  postgres:
    image: postgres:17-alpine 
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
volumes:
  postgres_db: