services:
  web:
    build: .
    ports:
    - 127.0.0.1:3000:80
    volumes:
      - ./data:/app/data
  tasks:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - MAPS_API_KEY=${MAPS_API_KEY}
    command: ["uv", "run", "python", "-m", "cashews.tasks"]
  postgres:
    image: postgres:17-alpine 
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
volumes:
  postgres_db: